// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dason.protobuf;

public interface StreamResquestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dason.gRPC.StreamResquest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   * @return The requestInfo.
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
