// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dason.protobuf;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dason.gRPC.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.dason.gRPC.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.dason.protobuf.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.dason.gRPC.StudentResponse studentResponse = 1;</code>
   */
  com.dason.protobuf.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.dason.gRPC.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.dason.gRPC.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.dason.protobuf.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.dason.gRPC.StudentResponse studentResponse = 1;</code>
   */
  com.dason.protobuf.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
